name: Setup Flutter

runs:
  using: "composite"
  steps:
    - uses: kuhnroyal/flutter-fvm-config-action@v3
    - name: Setup flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
        cache: true
    - name: Bootstrap App
      run: flutter pub get
      shell: bash
