# .github/workflows/setup-flutter.yml
name: Setup Flutter

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: kuhnroyal/flutter-fvm-config-action@v3
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - name: Bootstrap App
        run: flutter pub get
