name: Widgetbook

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Build widgetbook
        working-directory: widgetbook
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build web -t lib/main.dart
      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli
      - name: Push Widgetbook Build
        working-directory: widgetbook
        run: widgetbook cloud build push --commit ${{ github.event.pull_request.head.sha }} --api-key ${{ secrets.WIDGETBOOK_API_KEY }}
